[tasks.codegen]
description = "Update generated code"
run = "uv run python3 -m codegen.run"

[tasks.test]
description = "Run unit tests"
run = "uv run pytest -s"

[tasks.bench]
description = "Run benchmarks"
run = "uv run richbench benchmarks"
